In [1]:
%load_ext lab_black
%reload_ext lab_black

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime
from pathlib import Path
import seaborn as sns
import datetime
from plotly.subplots import make_subplots

WORK_DIR = Path.cwd()
ANALYSIS_DIR = WORK_DIR / "analysis"

In [3]:
import plotly.graph_objs as go

In [4]:
print(WORK_DIR)

/home/sam/Documents/projects/datascience

In [5]:
DATA_DIR = WORK_DIR / "data"

https://data.stadt-zuerich.ch/dataset/ugz_meteodaten_stundenmittelwerte

In [6]:
raw_meteo_df = pd.read_feather(DATA_DIR / "ugz_ogd_meteo_all.feather")
raw_covid_hospital_df = pd.read_feather(DATA_DIR / "hospital_capacity.feather")

In [7]:
_grp_ = raw_meteo_df.groupby(["Datum", "Parameter"])

agg_meteo_df = pd.DataFrame(
    dict(wert_mean=_grp_.Wert.mean(), einheit=_grp_.Einheit.first())
).reset_index()

In [15]:
agg_meteo_df

                     Datum Parameter   wert_mean einheit
0      2009-12-31 23:00:00        Hr   88.250000     %Hr
1      2009-12-31 23:00:00   RainDur    0.000000     min
2      2009-12-31 23:00:00    StrGlo    0.010000    W/m2
3      2009-12-31 23:00:00         T    5.590000      °C
4      2009-12-31 23:00:00        WD  156.570000       °
...                    ...       ...         ...     ...
765264 2021-01-09 23:00:00   RainDur    0.000000     min
765265 2021-01-09 23:00:00    StrGlo   54.100000    W/m2
765266 2021-01-09 23:00:00         T   -0.906667      °C
765267 2021-01-09 23:00:00  T_max_h1    0.310000      °C
765268 2021-01-09 23:00:00         p  969.736667     hPa

[765269 rows x 4 columns]

In [16]:
agg_temperatur_df = agg_meteo_df[agg_meteo_df.Parameter == "T"]

In [17]:
fig = go.Figure()

for parameter in agg_meteo_df.Parameter.drop_duplicates():
    _plot_df_ = agg_meteo_df[agg_meteo_df.Parameter == parameter]
    fig.add_trace(go.Scatter(x=_plot_df_.Datum, y=_plot_df_.wert_mean, name=parameter))


fig.show(renderer="browser")

## Covid Hospital Data

In [18]:
raw_covid_hospital_df.tail(5).T

,15493,15494,15495,15496,15497
date,2021-01-10 00:00:00,2021-01-10 00:00:00,2021-01-10 00:00:00,2021-01-10 00:00:00,2021-01-10 00:00:00
geoRegion,UR,VD,VS,LU,CH
ICU_AllPatients,3,93,21,39,713
ICU_Covid19Patients,3,48,9,20,394
ICU_Capacity,6,120,25,54,1036
Total_AllPatients,35,1336,759,703,16061
Total_Covid19Patients,11,337,65,124,2411
Total_Capacity,81,1928,966,1026,22930
ICU_NonCovid19Patients,0,45,12,19,319
ICU_FreeCapacity,3,27,4,15,323
Total_NonCovid19Patients,24,999,694,579,13650
Total_FreeCapacity,46,592,207,323,6869
timeframe_14d,True,True,True,True,True
timeframe_28d,True,True,True,True,True
timeframe_phase2,True,True,True,True,True
timeframe_phase2b,True,True,True,True,True
timeframe_all,True,True,True,True,True
Total_Capacity_mean15d,NaN,NaN,NaN,NaN,NaN
Total_AllPatients_mean15d,NaN,NaN,NaN,NaN,NaN
Total_Covid19Patients_mean15d,NaN,NaN,NaN,NaN,NaN
Total_NonCovid19Patients_mean15d,NaN,NaN,NaN,NaN,NaN
Total_FreeCapacity_mean15d,NaN,NaN,NaN,NaN,NaN
ICU_Capacity_mean15d,NaN,NaN,NaN,NaN,NaN
ICU_AllPatients_mean15d,NaN,NaN,NaN,NaN,NaN
ICU_Covid19Patients_mean15d,NaN,NaN,NaN,NaN,NaN
ICU_NonCovid19Patients_mean15d,NaN,NaN,NaN,NaN,NaN
ICU_FreeCapacity_mean15d,NaN,NaN,NaN,NaN,NaN
type_variant,fp7d,fp7d,fp7d,fp7d,fp7d
ICUPercent_AllPatients,50,77.5,84,72.2,68.8
ICUPercent_NonCovid19Patients,0,37.5,48,35.2,30.8
ICUPercent_Covid19Patients,50,40,36,37,38
ICUPercent_FreeCapacity,50,22.5,16,27.8,31.2
ICUPercent_Capacity,100,100,100,100,100
TotalPercent_AllPatients,43.2,69.3,78.6,68.5,70
TotalPercent_NonCovid19Patients,29.6,51.8,71.8,56.4,59.5
TotalPercent_Covid19Patients,13.6,17.5,6.7,12.1,10.5
TotalPercent_FreeCapacity,56.8,30.7,21.4,31.5,30
TotalPercent_Capacity,100,100,100,100,100
type,COVID19HospCapacity,COVID19HospCapacity,COVID19HospCapacity,COVID19HospCapacity,COVID19HospCapacity
version,2021-01-11_08-10-58,2021-01-11_08-10-58,2021-01-11_08-10-58,2021-01-11_08-10-58,2021-01-11_08-10-58

In [19]:
raw_covid_hospital_df[raw_covid_hospital_df.geoRegion == "CH"].sort_values("date").head(
    2
).T

                                                   26                   27
date                              2020-03-30 00:00:00  2020-03-30 00:00:00
geoRegion                                          CH                   CH
ICU_AllPatients                                   672                  693
ICU_Covid19Patients                               446                  453
ICU_Capacity                                     1197                 1239
Total_AllPatients                                6135                 6329
Total_Covid19Patients                            1308                 1328
Total_Capacity                                  14541                14953
ICU_NonCovid19Patients                            226                  240
ICU_FreeCapacity                                  525                  546
Total_NonCovid19Patients                         4827                 5001
Total_FreeCapacity                               8406                 8624
timeframe_14d                                   False                False
timeframe_28d                                   False                False
timeframe_phase2                                False                False
timeframe_phase2b                               False                False
timeframe_all                                    True                 True
Total_Capacity_mean15d                            NaN                  NaN
Total_AllPatients_mean15d                         NaN                  NaN
Total_Covid19Patients_mean15d                     NaN                  NaN
Total_NonCovid19Patients_mean15d                  NaN                  NaN
Total_FreeCapacity_mean15d                        NaN                  NaN
ICU_Capacity_mean15d                              NaN                  NaN
ICU_AllPatients_mean15d                           NaN                  NaN
ICU_Covid19Patients_mean15d                       NaN                  NaN
ICU_NonCovid19Patients_mean15d                    NaN                  NaN
ICU_FreeCapacity_mean15d                          NaN                  NaN
type_variant                                      nfp                 fp7d
ICUPercent_AllPatients                           56.1                 55.9
ICUPercent_NonCovid19Patients                    18.9                 19.4
ICUPercent_Covid19Patients                       37.3                 36.6
ICUPercent_FreeCapacity                          43.9                 44.1
ICUPercent_Capacity                               100                  100
TotalPercent_AllPatients                         42.2                 42.3
TotalPercent_NonCovid19Patients                  33.2                 33.4
TotalPercent_Covid19Patients                        9                  8.9
TotalPercent_FreeCapacity                        57.8                 57.7
TotalPercent_Capacity                             100                  100
type                              COVID19HospCapacity  COVID19HospCapacity
version                           2021-01-11_08-10-58  2021-01-11_08-10-58

In [20]:
raw_covid_hospital_df[
    (raw_covid_hospital_df.geoRegion == "CH")
    & (raw_covid_hospital_df.type_variant == "fp7d")
]

,date,geoRegion,ICU_AllPatients,ICU_Covid19Patients,ICU_Capacity,Total_AllPatients,Total_Covid19Patients,Total_Capacity,ICU_NonCovid19Patients,ICU_FreeCapacity,...,ICUPercent_Covid19Patients,ICUPercent_FreeCapacity,ICUPercent_Capacity,TotalPercent_AllPatients,TotalPercent_NonCovid19Patients,TotalPercent_Covid19Patients,TotalPercent_FreeCapacity,TotalPercent_Capacity,type,version
27,2020-03-30,CH,693.0,453.0,1239.0,6329.0,1328.0,14953.0,240.0,546.0,...,36.6,44.1,100.0,42.3,33.4,8.9,57.7,100.0,COVID19HospCapacity,2021-01-11_08-10-58
79,2020-03-31,CH,741.0,487.0,1277.0,6681.0,1440.0,15714.0,254.0,536.0,...,38.1,42.0,100.0,42.5,33.4,9.2,57.5,100.0,COVID19HospCapacity,2021-01-11_08-10-58
130,2020-04-01,CH,768.0,514.0,1338.0,7491.0,1631.0,17605.0,254.0,570.0,...,38.4,42.6,100.0,42.6,33.3,9.3,57.4,100.0,COVID19HospCapacity,2021-01-11_08-10-58
175,2020-04-02,CH,784.0,493.0,1328.0,8129.0,1680.0,18604.0,291.0,544.0,...,37.1,41.0,100.0,43.7,34.7,9.0,56.3,100.0,COVID19HospCapacity,2021-01-11_08-10-58
221,2020-04-03,CH,767.0,482.0,1309.0,8168.0,1658.0,19324.0,285.0,542.0,...,36.8,41.4,100.0,42.3,33.7,8.6,57.7,100.0,COVID19HospCapacity,2021-01-11_08-10-58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15228,2021-01-06,CH,784.0,438.0,1045.0,16744.0,2611.0,22839.0,346.0,261.0,...,41.9,25.0,100.0,73.3,61.9,11.4,26.7,100.0,COVID19HospCapacity,2021-01-11_08-10-58
15308,2021-01-07,CH,787.0,420.0,1035.0,16898.0,2462.0,22853.0,367.0,248.0,...,40.6,24.0,100.0,73.9,63.2,10.8,26.1,100.0,COVID19HospCapacity,2021-01-11_08-10-58
15342,2021-01-08,CH,783.0,408.0,1040.0,16673.0,2387.0,22852.0,375.0,257.0,...,39.2,24.7,100.0,73.0,62.5,10.4,27.0,100.0,COVID19HospCapacity,2021-01-11_08-10-58
15390,2021-01-09,CH,731.0,396.0,1038.0,15972.0,2381.0,22765.0,335.0,307.0,...,38.2,29.6,100.0,70.2,59.7,10.5,29.8,100.0,COVID19HospCapacity,2021-01-11_08-10-58
15497,2021-01-10,CH,713.0,394.0,1036.0,16061.0,2411.0,22930.0,319.0,323.0,...,38.0,31.2,100.0,70.0,59.5,10.5,30.0,100.0,COVID19HospCapacity,2021-01-11_08-10-58

In [21]:
raw_covid_hospital_df.type.drop_duplicates()

0    COVID19HospCapacity
Name: type, dtype: object

In [22]:
_cols_ = [
    "date",
    "Total_Covid19Patients",
    "ICU_Covid19Patients",
    # "ICU_Capacity",
    "ICU_NonCovid19Patients",
    "ICU_FreeCapacity",
]
agg_covid_patients_df = raw_covid_hospital_df.loc[
    (raw_covid_hospital_df.geoRegion == "CH")
    & (raw_covid_hospital_df.type_variant == "fp7d"),
    _cols_,
]

In [23]:
agg_covid_patients_df

,date,Total_Covid19Patients,ICU_Covid19Patients,ICU_NonCovid19Patients,ICU_FreeCapacity
27,2020-03-30,1328.0,453.0,240.0,546.0
79,2020-03-31,1440.0,487.0,254.0,536.0
130,2020-04-01,1631.0,514.0,254.0,570.0
175,2020-04-02,1680.0,493.0,291.0,544.0
221,2020-04-03,1658.0,482.0,285.0,542.0
...,...,...,...,...,...
15228,2021-01-06,2611.0,438.0,346.0,261.0
15308,2021-01-07,2462.0,420.0,367.0,248.0
15342,2021-01-08,2387.0,408.0,375.0,257.0
15390,2021-01-09,2381.0,396.0,335.0,307.0
15497,2021-01-10,2411.0,394.0,319.0,323.0

In [28]:
cols_plus_color = {
    "ICU_Covid19Patients": "red",
    "ICU_NonCovid19Patients": "orange",
    "ICU_FreeCapacity": "green",
}

fig = go.Figure()
for col in cols_plus_color.keys():
    fig.add_trace(
        go.Scatter(
            x=agg_covid_patients_df.date,
            y=agg_covid_patients_df[col],
            name=col,
            line=dict(width=0.5, color=cols_plus_color[col]),
            opacity=0.5,
            stackgroup="one",
            groupnorm="percent",  # sets the normalization for the sum of the stackgroup
        )
    )
fig.update_layout(barmode="stack")  # relative
# fig.update_layout(barmode="relative")
fig.update_layout(
    updatemenus=[
        dict(
            buttons=list(
                [
                    dict(
                        args=["groupnorm", "percent"],
                        label="Percentage",
                        method="restyle",
                    ),
                    dict(
                        args=["groupnorm", "total"],
                        label="Stacked Totals",
                        method="restyle",
                    ),
                ]
            ),
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=1.02,
            xanchor="left",
            y=0.9,
            yanchor="top",
        ),
    ]
)
fig.update_layout(hovermode="x unified")
fig.write_html(str(WORK_DIR / "analysis" / "hospital_capacity_time_series.html"))
fig.show(renderer="browser")

In [29]:
agg_covid_patients_df

,date,Total_Covid19Patients,ICU_Covid19Patients,ICU_NonCovid19Patients,ICU_FreeCapacity
27,2020-03-30,1328.0,453.0,240.0,546.0
79,2020-03-31,1440.0,487.0,254.0,536.0
130,2020-04-01,1631.0,514.0,254.0,570.0
175,2020-04-02,1680.0,493.0,291.0,544.0
221,2020-04-03,1658.0,482.0,285.0,542.0
...,...,...,...,...,...
15228,2021-01-06,2611.0,438.0,346.0,261.0
15308,2021-01-07,2462.0,420.0,367.0,248.0
15342,2021-01-08,2387.0,408.0,375.0,257.0
15390,2021-01-09,2381.0,396.0,335.0,307.0
15497,2021-01-10,2411.0,394.0,319.0,323.0

# fbprophet

In [30]:
from ade_corona_tools import create_prophet_dataframe, plot_forecast

In [31]:
agg_meteo_df.Parameter.drop_duplicates()

0               Hr
1          RainDur
2           StrGlo
3                T
4               WD
5              WVs
6              WVv
7                p
765222    T_max_h1
Name: Parameter, dtype: object

In [39]:
agg_meteo_df[agg_meteo_df.Parameter == "T"].sort_values("Datum").tail(5)

                     Datum Parameter  wert_mean einheit
765246 2021-01-05 23:00:00         T   0.346667      °C
765251 2021-01-06 23:00:00         T   1.636667      °C
765256 2021-01-07 23:00:00         T   0.723333      °C
765261 2021-01-08 23:00:00         T  -1.460000      °C
765266 2021-01-09 23:00:00         T  -0.906667      °C

In [47]:
forecast = create_prophet_dataframe(
    agg_temperatur_df=agg_meteo_df[agg_meteo_df.Parameter == "T"],
    ds="Datum",
    y="wert_mean",
    daily=True,
    weekly=False,
    freq="H",
    number_freq_into_future=24 * 30 * 30,
)

In [41]:
agg_covid_patients_df.tail(5)

,date,Total_Covid19Patients,ICU_Covid19Patients,ICU_NonCovid19Patients,ICU_FreeCapacity
15228,2021-01-06,2611.0,438.0,346.0,261.0
15308,2021-01-07,2462.0,420.0,367.0,248.0
15342,2021-01-08,2387.0,408.0,375.0,257.0
15390,2021-01-09,2381.0,396.0,335.0,307.0
15497,2021-01-10,2411.0,394.0,319.0,323.0

forecast = create_prophet_dataframe(
    agg_covid_patients_df,
    ds="date",
    y="Total_Covid19Patients",
    weekly=True,
    daily=False,
    freq="D",
    number_freq_into_future=24 * 30 * 30,
)

In [49]:
forecast

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,daily,...,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat,y,trend_changepoint,weekly,weekly_lower,weekly_upper
0,2009-12-31 23:00:00,9.200693,-5.232115,4.546156,9.200693,9.200693,-9.243158,-9.243158,-9.243158,-1.290082,...,-7.953076,0.0,0.0,0.0,-0.042465,5.59,NaN,0,0,0
1,2010-01-01 00:00:00,9.201326,-4.836693,4.428713,9.201326,9.201326,-9.566875,-9.566875,-9.566875,-1.611858,...,-7.955017,0.0,0.0,0.0,-0.365549,5.37,NaN,0,0,0
2,2010-01-01 01:00:00,9.201960,-5.672967,4.380689,9.201960,9.201960,-9.864930,-9.864930,-9.864930,-1.907960,...,-7.956970,0.0,0.0,0.0,-0.662970,4.96,NaN,0,0,0
3,2010-01-01 02:00:00,9.202593,-5.678652,3.982364,9.202593,9.202593,-10.133513,-10.133513,-10.133513,-2.174578,...,-7.958935,0.0,0.0,0.0,-0.930920,4.69,NaN,0,0,0
4,2010-01-01 03:00:00,9.203226,-6.002822,3.678183,9.203226,9.203226,-10.350333,-10.350333,-10.350333,-2.389420,...,-7.960912,0.0,0.0,0.0,-1.147106,5.25,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118036,2023-06-28 19:00:00,12.318142,-1.219950,43.773968,-10.330775,34.273677,9.410184,9.410184,9.410184,0.498483,...,8.911701,0.0,0.0,0.0,21.728326,NaN,NaN,0,0,0
118037,2023-06-28 20:00:00,12.318140,-2.016342,43.949439,-10.331310,34.275470,8.847704,8.847704,8.847704,-0.068419,...,8.916123,0.0,0.0,0.0,21.165843,NaN,NaN,0,0,0
118038,2023-06-28 21:00:00,12.318137,-1.954747,43.332878,-10.331844,34.277264,8.381051,8.381051,8.381051,-0.539488,...,8.920539,0.0,0.0,0.0,20.699188,NaN,NaN,0,0,0
118039,2023-06-28 22:00:00,12.318134,-2.163917,43.138392,-10.332378,34.279058,7.987209,7.987209,7.987209,-0.937740,...,8.924949,0.0,0.0,0.0,20.305343,NaN,NaN,0,0,0
118040,2023-06-28 23:00:00,12.318131,-2.072122,41.842881,-10.332912,34.280852,7.639270,7.639270,7.639270,-1.290082,...,8.929352,0.0,0.0,0.0,19.957401,NaN,12.318131,0,0,0

In [50]:
plot_forecast(forecast=forecast, analysis_dir=ANALYSIS_DIR)

This is the format of your plot grid:
[ (1,1) x,y             -      ]  [ (1,3) x2,y2 ]
[ (2,1) x3,y3           -      ]  [ (2,3) x4,y4 ]
[ (3,1) x5,y5 ]  [ (3,2) x6,y6 ]  [ (3,3) x7,y7 ]

/home/sam/Documents/projects/datascience/analysis/fft_deconstruction.html

# Combine hospital counts with globale strahlung

In [44]:
agg_covid_patients_df

,date,Total_Covid19Patients,ICU_Covid19Patients,ICU_NonCovid19Patients,ICU_FreeCapacity
27,2020-03-30,1328.0,453.0,240.0,546.0
79,2020-03-31,1440.0,487.0,254.0,536.0
130,2020-04-01,1631.0,514.0,254.0,570.0
175,2020-04-02,1680.0,493.0,291.0,544.0
233,2020-04-03,1658.0,482.0,285.0,542.0
...,...,...,...,...,...
15044,2021-01-02,2571.0,421.0,302.0,307.0
15084,2021-01-03,2664.0,428.0,308.0,296.0
15143,2021-01-04,2699.0,434.0,337.0,268.0
15174,2021-01-05,2692.0,443.0,334.0,265.0
15281,2021-01-06,2611.0,438.0,346.0,261.0

In [51]:
forecast["date"] = forecast.ds.dt.date

In [77]:
forecast.columns

Index(['ds', 'trend', 'yhat_lower', 'yhat_upper', 'trend_lower', 'trend_upper',
       'additive_terms', 'additive_terms_lower', 'additive_terms_upper',
       'daily', 'daily_lower', 'daily_upper', 'yearly', 'yearly_lower',
       'yearly_upper', 'multiplicative_terms', 'multiplicative_terms_lower',
       'multiplicative_terms_upper', 'yhat', 'y', 'trend_changepoint',
       'weekly', 'weekly_lower', 'weekly_upper', 'date'],
      dtype='object')

In [78]:
_grp_ = forecast.groupby("date")

globale_strahlung_df = (
    pd.DataFrame({"strglo_yearly": _grp_.yearly.mean(), "strglo_y": _grp_.y.mean()})
    .reset_index()
    .astype({"date": "datetime64[ns]"})
)

In [107]:
globale_strahlung_df["rolling_mean_y"] = globale_strahlung_df.strglo_y.rolling(
    14
).mean()

In [108]:
globale_strahlung_df.sample(10)

           date  strglo_yearly    strglo_y  rolling_mean_y
4569 2022-07-05     127.317701         NaN             NaN
737  2012-01-07    -102.529158   11.498333       33.996190
1765 2014-10-31     -72.341565   92.357826       84.225886
770  2012-02-09     -74.069436   77.769167       59.077143
897  2012-06-15      93.187375  334.317083      192.770000
3891 2020-08-26      49.553314  239.292083      208.385327
776  2012-02-15     -66.957255   12.790833       74.768482
2889 2017-11-28    -102.809020   28.530833       39.119405
334  2010-11-30    -103.491889   69.462917       34.716399
643  2011-10-05     -31.102868  120.384583      148.751815

In [109]:
combination_df = pd.merge(
    agg_covid_patients_df,
    globale_strahlung_df,
    left_on="date",
    right_on="date",
    how="right",
)

In [110]:
combination_df

,date,Total_Covid19Patients,ICU_Covid19Patients,ICU_NonCovid19Patients,ICU_FreeCapacity,strglo_yearly,strglo_y,rolling_mean_y
0,2009-12-31,NaN,NaN,NaN,NaN,-103.227593,0.010000,NaN
1,2010-01-01,NaN,NaN,NaN,NaN,-103.126202,14.469583,NaN
2,2010-01-02,NaN,NaN,NaN,NaN,-102.955318,52.862917,NaN
3,2010-01-03,NaN,NaN,NaN,NaN,-102.817659,71.705417,NaN
4,2010-01-04,NaN,NaN,NaN,NaN,-102.709527,68.614583,NaN
...,...,...,...,...,...,...,...,...
4919,2023-06-20,NaN,NaN,NaN,NaN,99.116760,NaN,NaN
4920,2023-06-21,NaN,NaN,NaN,NaN,101.156729,NaN,NaN
4921,2023-06-22,NaN,NaN,NaN,NaN,103.378510,NaN,NaN
4922,2023-06-23,NaN,NaN,NaN,NaN,105.740365,NaN,NaN
4923,2023-06-24,NaN,NaN,NaN,NaN,108.196008,NaN,NaN

In [115]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=combination_df.date,
        y=combination_df.ICU_Covid19Patients,
        name="ICU_Covid19Patients",
        opacity=0.5,
    )
)
fig.add_trace(
    go.Scatter(
        x=combination_df.date,
        y=combination_df.strglo_yearly,
        name="strglo_yearly",
        opacity=0.5,
    )
)


fig.add_trace(
    go.Scatter(
        x=combination_df.date,
        y=combination_df.rolling_mean_y - 52,
        name="f(rolling_mean_y)",
        opacity=0.5,
    )
)
# fig.update_layout(barmode="stack")  # relative
fig.show(renderer="browser")

# TESt

In [170]:
z_data = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/api_docs/mt_bruno_elevation.csv"
)
z = z_data.values
sh_0, sh_1 = z.shape
x, y = np.linspace(0, 1, sh_0), np.linspace(0, 1, sh_1)
fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
fig.update_layout(
    title="Mt Bruno Elevation",
    autosize=True,
    # width=500,
    # height=500,
    # margin=dict(l=65, r=50, b=65, t=90),
)
fig.show(renderer="browser")

In [167]:
len(x)

25

In [173]:
len(z[0])

25

In [174]:
len(y)

25

In [175]:
file_dir = WORK_DIR / "data" / "bag" / "data" / "COVID19Death_geoRegion_AKL10_w.csv"

In [228]:
covid_death_df = pd.read_csv(file_dir).drop(
    columns=[
        "type",
        "type_variant",
        "version",
        "timeframe_all",
        "timeframe_phase2",
        "timeframe_phase2b",
        "timeframe_28d",
        "timeframe_14d",
    ]
)

In [229]:
covid_death_ch_df = covid_death_df[
    (covid_death_df.geoRegion == "CH")
    & (covid_death_df.altersklasse_covid19 != "Unbekannt")
]
date_sundays = (covid_death_ch_df.datum_dboardformated + "-7").apply(
    lambda x: datetime.strptime(x, "%G-%V-%u")
)

covid_death_ch_df.loc[:, "date_sundays"] = date_sundays

/home/sam/.virtualenvs/datascience/lib/python3.8/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/sam/.virtualenvs/datascience/lib/python3.8/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [230]:
covid_death_ch_df

,altersklasse_covid19,geoRegion,datum,entries,sumTotal,freq,prct,pop,inz_entries,inzsumTotal,datum_unit,datum_dboardformated,date_sundays
0,0 - 9,CH,202009,0,0,NaN,NaN,873043.0,0.00,0.00,isoweek,2020-09,2020-03-01
1,0 - 9,CH,202010,0,0,0.000,0.0,873043.0,0.00,0.00,isoweek,2020-10,2020-03-08
2,0 - 9,CH,202011,0,0,0.000,0.0,873043.0,0.00,0.00,isoweek,2020-11,2020-03-15
3,0 - 9,CH,202012,0,0,0.000,0.0,873043.0,0.00,0.00,isoweek,2020-12,2020-03-22
4,0 - 9,CH,202013,0,0,0.000,0.0,873043.0,0.00,0.00,isoweek,2020-13,2020-03-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,80+,CH,202050,417,4175,0.729,72.9,453670.0,91.92,920.27,isoweek,2020-50,2020-12-13
410,80+,CH,202051,453,4628,0.758,75.8,453670.0,99.85,1020.12,isoweek,2020-51,2020-12-20
411,80+,CH,202052,388,5016,0.712,71.2,453670.0,85.52,1105.65,isoweek,2020-52,2020-12-27
412,80+,CH,202053,315,5331,0.709,70.9,453670.0,69.43,1175.08,isoweek,2020-53,2021-01-03
413,80+,CH,202101,113,5444,0.720,72.0,453670.0,24.91,1199.99,isoweek,2021-01,2021-01-10

In [234]:
fig = go.Figure()
for (col, data) in covid_death_ch_df.groupby("altersklasse_covid19"):
    fig.add_trace(go.Bar(x=data.date_sundays, y=data.entries, name=col))
fig.update_layout(barmode="stack", xaxis={"categoryorder": "category ascending"})
fig.show(renderer="browser")

In [235]:
_grp_ = covid_death_ch_df.groupby("altersklasse_covid19")
pie_of_death_df = pd.DataFrame({"sum_total": _grp_.entries.sum()}).reset_index()

In [236]:
pie_of_death_df

  altersklasse_covid19  sum_total
0                0 - 9          2
1              10 - 19          0
2              20 - 29          3
3              30 - 39          8
4              40 - 49         21
5              50 - 59        122
6              60 - 69        447
7              70 - 79       1498
8                  80+       5444

In [247]:
fig = go.Figure()

fig.add_trace(
    go.Bar(
        y=pie_of_death_df.altersklasse_covid19,
        x=pie_of_death_df.sum_total,
        text=pie_of_death_df.sum_total.astype(str),
        orientation="h",
        opacity=0.5,
    )
)
fig.update_traces(texttemplate="%{text:.2s}", textposition="outside")
fig.show(renderer="browser")